### PR TITLE
basic Priors

### PR DESCRIPTION
**Pull request by francescoalemanno**
Adding Factored to base package

### CODE REVIEW

**Comment by jbrea** [comment]
After efords comment jbrea/LikelihoodfreeInference.jl#5 I thought it may be a good idea to move the priors to Distributions.jl. There is also [this discussion in discourse](https://discourse.julialang.org/t/questions-about-contributing-to-distributions-jl/41530/35). What do you think?

**Comment by francescoalemanno** [comment]
It is a very good idea, but i think that it will seriously hinder the speed at which we can create a workable solution.
For example `Distributions.jl` already has a factored distribution (it is called `Product`), but it doesnt support mixing continuous  and discrete distributions, and ofcourse since `Product` is based on arrays, it is not possible to extend it and have it type stable at the same time. Thus i know for sure that `Distributions` is not going to accept a PR with `Factored` inside

**Comment by francescoalemanno** [comment]
i will merge this, just to start working on it, we can excise this code anytime ;)

**Comment by jbrea** [comment]
Yes. This makes total sense. We can put whatever we want here for now and move it to other packages anytime later.

**Pull request merged**
